# Generated by Django 5.0.6 on 2024-05-13 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IotDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('typeOfDevice', models.CharField(max_length=100)),
                ('deviceName', models.CharField(max_length=100)),
                ('deviceURI', models.CharField(max_length=100)),
                ('deviceDescription', models.TextField()),
                ('deviceStatus', models.BooleanField(default=False)),
                ('deviceImage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('deviceOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
