# Generated by Django 5.0.6 on 2024-06-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_user_city_alter_user_street_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='area_of_interest',
        ),
        migrations.AddField(
            model_name='user',
            name='area_of_interest',
            field=models.ManyToManyField(blank=True, null=True, to='common.areaofinterest'),
        ),
    ]
