# Generated by Django 5.1.1 on 2024-10-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_user_motivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_debate_points_interesting', models.IntegerField(default=0)),
                ('voter_debate_points_trust', models.IntegerField(default=0)),
                ('voter_debate_points_not_trust', models.IntegerField(default=0)),
                ('voter_debate_points_agree', models.IntegerField(default=0)),
                ('voter_debate_points_not_agree', models.IntegerField(default=0)),
                ('voter_debate_points_proposal', models.IntegerField(default=0)),
            ],
        ),
    ]
