# Generated by Django 5.1.1 on 2024-10-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_setting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='voter_debate_points_agree',
            new_name='voter_debate_points_comp_proposal',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='voter_debate_points_interesting',
            new_name='voter_debate_points_con_arg',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='voter_debate_points_not_agree',
            new_name='voter_debate_points_fact',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='voter_debate_points_not_trust',
            new_name='voter_debate_points_improvment',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='voter_debate_points_proposal',
            new_name='voter_debate_points_pro_arg',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='voter_debate_points_trust',
            new_name='voter_debate_points_question',
        ),
    ]
