# Generated by Django 5.0.6 on 2024-07-06 13:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='likes',
        ),
        migrations.CreateModel(
            name='DebateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('contentLinks', models.ManyToManyField(blank=True, null=True, to='channels.news')),
                ('debateCardLinks', models.ManyToManyField(blank=True, null=True, to='channels.debatecard')),
            ],
        ),
        migrations.CreateModel(
            name='DebatePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('point', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
