# Generated by Django 5.1.1 on 2024-10-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_debatepoint_card_debatepoint_type_alter_news_image'),
        ('content', '0002_tag_proposal_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='content.tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='content.tag'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='content.tag'),
        ),
    ]
