# Generated by Django 5.0.6 on 2024-07-06 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_debatecard_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debatepoint',
            name='point',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(-1)]),
        ),
    ]
