# Generated by Django 5.0.7 on 2024-08-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='showOnlyImage',
            field=models.BooleanField(default=False),
        ),
    ]
