# Generated by Django 5.0.4 on 2024-05-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='qrCode',
            field=models.ImageField(blank=True, null=True, upload_to='events/qrcodes/'),
        ),
    ]
