# Generated by Django 5.1.1 on 2024-10-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_alter_news_tag_alter_project_tag_and_more'),
        ('content', '0002_tag_proposal_tag'),
        ('events', '0002_event_showonlyimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='event',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='content.tag'),
        ),
    ]
